### ISSUE TITLE
Improve QA bots with GH Actions

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#100]
Our crowdsourced [Crypto Attack Wiki](https://github.com/1712n/dn-institute/tree/main/content/attacks) has a [number of bots](https://github.com/1712n/dn-institute/tree/main/.github/workflows) in charge of automated quality checks. To participate in the challenge, submit a pull request that adds or modifies existing bots and request a review from this issue assignees. Below are some improvement ideas, but feel free to suggest other functionality.

```[tasklist]
### Tasks
- [ ] Improving existing fact-checker
- [ ] Advanced spell-checking [based on LanguageTool](https://github.com/reviewdog/action-languagetool)
- [ ] Plagiarism detector
- [ ] Prettifying markdown on merge
- [ ] [AI-written text detector](https://openai.com/blog/new-ai-classifier-for-indicating-ai-written-text)
- [ ] Hugo SSG formatting
```

[Wiki submission guidelines](https://github.com/1712n/dn-institute#readme) are another source of needed functionality inspiration. All submissions will be reviewed by the wiki maintainers, and additional changes to your pull request may be asked of you to bring your submission to improve code quality, security, and/or efficiency.

### How to Claim Bounty
Email your bitcoin or stablecoin payment address to [wiki.challenge.bounties@dn.institute](mailto:wiki.challenge.bounties@dn.institute). Expect all payouts to be completed by the end of the month.
